# N-NODE CLUSTER

Vagrant.configure("2") do |config|

  config.vm.provision "shell", inline: <<-EOL
  echo "Setting up your cluster sandbox..."
  EOL

  config.vm.box = "centos/8"
  config.vbguest.auto_update = false
  # config.vbguest.auto_update = true

  # PROVISION NODES AS PER YOUR REQUIREMENT
  WN_COUNT = 3                    # change the no. to your desired count, make sure you have the required resources 
  (1..WN_COUNT).each do |i|
    config.vm.define "vm-#{i}" do |no|
      no.vm.provision "shell", inline: <<-EOL 
      echo "Provisioning vm-#{i}..."
      EOL

      no.vm.hostname = "vm-#{i}"
      
      no.vm.network "private_network", ip: "192.168.10.#{10+i}"

      # VIRTUAL BOX RESOURCE LIMITS FOR WORKER NODE
      no.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = 1024
      end

    end 

  end 

end